language: php
sudo: required
dist: trusty
php:
- 7.2
before_install:
- composer self-update
before_script:
- composer install --no-interaction
script:
- phpdbg -qrr ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php --coverage-clover=coverage.xml tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
