language: php
sudo: required
dist: trusty
php:
- 7.2
before_install:
- composer self-update
before_script:
- composer install --no-interaction
script:
- phpdbg -qrr ./vendor/bin/phpunit --bootstrap --coverage-clover=coverage.xml ./vendor/autoload.php tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
